// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// ignore: depend_on_referenced_packages
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoux_1JTe9IV5w_RVG0M12ScsmBxwRXAs',
    appId: '1:483265850320:web:020a9f494b1f6230fb27d5',
    messagingSenderId: '483265850320',
    projectId: 'flutter-login-project-9ad83',
    authDomain: 'flutter-login-project-9ad83.firebaseapp.com',
    storageBucket: 'flutter-login-project-9ad83.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZRhDhuyvH2fTMEQCIIU7P-8mMOKTGK4I',
    appId: '1:483265850320:android:9a70f836ebd71344fb27d5',
    messagingSenderId: '483265850320',
    projectId: 'flutter-login-project-9ad83',
    storageBucket: 'flutter-login-project-9ad83.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_VIxFgnqwlRjgB8MFX4uKXQ2GwrGwMLE',
    appId: '1:483265850320:ios:0f8668f8d6888f94fb27d5',
    messagingSenderId: '483265850320',
    projectId: 'flutter-login-project-9ad83',
    storageBucket: 'flutter-login-project-9ad83.appspot.com',
    iosClientId:
        '483265850320-9v1psiieehqnfi5uv3uslvg1lqtf1uoh.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTodoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_VIxFgnqwlRjgB8MFX4uKXQ2GwrGwMLE',
    appId: '1:483265850320:ios:0f8668f8d6888f94fb27d5',
    messagingSenderId: '483265850320',
    projectId: 'flutter-login-project-9ad83',
    storageBucket: 'flutter-login-project-9ad83.appspot.com',
    iosClientId:
        '483265850320-9v1psiieehqnfi5uv3uslvg1lqtf1uoh.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTodoApp',
  );
}
